import Head from 'next/head'
import Slider from '../components/Slider'
import Hero from '../components/Hero'
import {SliderData} from '../components/SliderData'
import Instagram from '../components/Instagram'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Photographer Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Capture Photography' message='I capture moments in nature and keep
      them alive.' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
